### ISSUE TITLE
'bgc' package not found

### ISSUE THREAD

**Issue by vpaba** [euroargodev/BBP_RTQC#1]
Hi @grgdll,

Thanks for developing this notebook. @kamwal and I have been trying it out, and found a blocker which we were hoping you could help us with.

In the third cell ('Import needed modules'), a package named 'bgc' is called, which we have been unable to find and install:

`from bgc import plot_bbp, plot_flags, medfilt1`

We were wondering how we may access this package?

Thanks,
Violetta

**Comment by grgdll** [comment]
Hi @vpaba, 
apologies that was a file that I had forgotten to upload, although it may not be crucial.
It's in the repository now.
Please let me know if this helps.
Cheers,
grg
