### ISSUE TITLE
 iParkPres bugs #L893

### ISSUE THREAD

**Issue by haijijie** [euroargodev/BBP_RTQC#4]
https://github.com/euroargodev/BBP_RTQC/blob/00465e5539166c6fd4b68484eefe05332b0ecbbe/BBP_RTQC.py#L893
old one:
    iParkPres = np.where(ds_config.CONFIG_PARAMETER_NAME.astype('str').str.contains('CONFIG_ParkPressure_dbar'))[0][0]
    PARK_PRES = ds_config.CONFIG_PARAMETER_VALUE.values[i_miss_no,iParkPres]
    if np.isnan(PARK_PRES):
        # assume PARK_PRES=1000 dbars
        PARK_PRES = 1000.

new one:
    PARK_PRES = 1000
    if sum(ds_config.CONFIG_PARAMETER_NAME.astype('str').str.contains('CONFIG_ParkPressure_dbar'))>=1:
        iParkPres = np.where(ds_config.CONFIG_PARAMETER_NAME.astype('str').str.contains('CONFIG_ParkPressure_dbar'))[0][0]
        PARK_PRES = ds_config.CONFIG_PARAMETER_VALUE.values[i_miss_no,iParkPres]
    if np.isnan(PARK_PRES):
        # assume PARK_PRES=1000 dbars
        PARK_PRES = 1000.

Comments:
If ds_config.CONFIG_PARAMETER_NAME not contains 'CONFIG_ParkPressure_dbar', np.where() is empty, [0][0] is a bug

**Comment by grgdll** [comment]
But if np.where() is empty, then the code should stop with an error. This has never happend to me. Did you get this error? If not, then it means that "CONFIG_ParkPressure_dbar" is always defined.
