### ISSUE TITLE
KHI_BACKSCATTERING700 missing

### ISSUE THREAD

**Issue by haijijie** [euroargodev/BBP_RTQC#5]
https://github.com/euroargodev/BBP_RTQC/blob/00465e5539166c6fd4b68484eefe05332b0ecbbe/BBP_RTQC.py#L795

old codes:
            for text in calcoeff_string.split(delim):
                if "DARK_BACKSCATTERING700" in text:
                    DARK_BACKSCATTERING700 = float(text.split("=")[-1])
                elif "khi" in text:
                    KHI_BACKSCATTERING700 = float(text.split("=")[-1])
                elif "SCALE_BACKSCATTERING700" in text:
                    SCALE_BACKSCATTERING700 = float(text.split("=")[-1])
modified codes:
            SCALE_BACKSCATTERING700 = 125 # different flag from above to differentiate them
            DARK_BACKSCATTERING700 = 125
            KHI_BACKSCATTERING700 = 125
            for text in calcoeff_string.split(delim):
                if "DARK_BACKSCATTERING700" in text:
                    DARK_BACKSCATTERING700 = float(text.split("=")[-1])
                elif "khi" in text:
                    KHI_BACKSCATTERING700 = float(text.split("=")[-1])
                elif "SCALE_BACKSCATTERING700" in text:
                    SCALE_BACKSCATTERING700 = float(text.split("=")[-1])

Comment:
Better to initialize these parameters before assignment, in case there is part of (not all) parameters mising in the meta file:

**Comment by grgdll** [comment]
Thanks!
